hospins/Areas/EmployeePanel/Controllers/LogbookController.cs
using hospins.Extensions;
using hospins.Infrastructure;
using hospins.Models;
using hospins.Repository.Data;
using hospins.Repository.Infrastructure;
using hospins.Repository.ServiceContract;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data.SqlClient;

namespace hospins.Areas.EmployeePanel.Controllers
{
    [UserAuthorize]
    public class LogbookController : EmployeePanelBaseControllerBase
    {
        private readonly IServiceProvider _serviceProvider;
        private readonly ICommonRepository<Category> _ICategoryRepository;
        private readonly ICommonRepository<SubCategory> _ISubCategoryRepository;
        private readonly ICommonRepository<Priority> _IPriorityRepository;
        private readonly ICommonRepository<Logbook> _ILogbookRepository;
        public LogbookController(IServiceProvider _service,
        ICommonRepository<Category> iCategoryRepository,
        ICommonRepository<SubCategory> iSubCategoryRepository,
        ICommonRepository<Priority> iPriorityRepository,
        ICommonRepository<Logbook> iLogbookRepository)
        {
            _serviceProvider = _service;
            _ICategoryRepository = iCategoryRepository;
            _ISubCategoryRepository = iSubCategoryRepository;
            _IPriorityRepository = iPriorityRepository;
            _ILogbookRepository = iLogbookRepository;
        }

        #region :: CATEGORY ::
        public IActionResult Category()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ManageCategory(int id = 0)
        {
            var category = new CategoryModel();
            try
            {
                if (id != 0)
                {
                    category = _ICategoryRepository.GetById(id).ToModel();
                    
                }
                return PartialView(category);
            }
            catch (Exception ex)
            {
                ex.SetLog("Logbook/ManageCategory");
                return PartialView(category);
            }
        }

        [HttpPost]
        public IActionResult ManageCategory(CategoryModel category)
        {
            try
            {
                var ObjCategory = category.CategoryId != 0 ? _ICategoryRepository.GetByIdWithNoTracking(category.CategoryId) : null;
                if (ObjCategory == null || !string.Equals(ObjCategory.Name.Trim().ToLower(), category.Name.Trim().ToLower(), StringComparison.OrdinalIgnoreCase))
                {
                    var categoryDb = _ICategoryRepository.GetAll(x => string.Equals(x.Name.Trim().ToLower(), category.Name.Trim().ToLower()) && !x.IsDelete).FirstOrDefault();
                    if (categoryDb != null)
                        return Json(new { success = "false", ReturnMsg = "Category already exists.", PartialviewContent = this.RenderPartialViewToString("ManageCategory", category, _serviceProvider) });
                }
                if (ModelState.IsValid)
                {
                    if (category.CategoryId == 0)
                    {
                        Category CategoryObj = _ICategoryRepository.InsertAndGetObj(category.ToEntity(), CurrentContext.UserDetail.UserId);
                        return Json(new { success = "true", ReturnMsg = "Category saved.", PartialviewContent = "" });
                    }
                    else
                    {
                        _ICategoryRepository.Update(category.ToEntity(), CurrentContext.UserDetail.UserId);
                        return Json(new { success = "true", ReturnMsg = "Category updated.", PartialviewContent = "" });
                    }
                }
                else
                {
                    string _message = string.Join(Environment.NewLine, ModelState.Values
                                               .SelectMany(x => x.Errors)
                                               .Select(x => x.ErrorMessage));
                    return Json(new { success = "false", ReturnMsg = _message, PartialviewContent = this.RenderPartialViewToString("ManageCategory", category, _serviceProvider) });
                }
            }
            catch (Exception ex)
            {
                ex.SetLog("Logbook/ManageCategory");
                return Json(new { success = "false", ReturnMsg = ex.Message, PartialviewContent = this.RenderPartialViewToString("ManageCategory", category, _serviceProvider) });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult StatusCategory(int Id)
        {
            try
            {
                var category = _ICategoryRepository.GetById(Id);
                if (category != null)
                {
                    category.IsActive = category.IsActive = !category.IsActive;
                    _ICategoryRepository.Update(category, CurrentContext.UserDetail.UserId, "status");
                    return Json(new { success = "true", ReturnMsg = "Category status change successfully.", PartialviewContent = "" });
                }
                else
                {
                    return Json(new { success = "false", ReturnMsg = "Category does not exist.", PartialviewContent = "" });
                }
            }
            catch (Exception ex)
            {
                ex.SetLog("Master/StatusCategory");
                return Json(new { success = "false", ReturnMsg = "Error", PartialviewContent = "" });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteMultipleCategory(string Id)
        {
            try
            {
                if (Id != null)
                {
                    //var ids = Id.Split(",").Select(t => Convert.ToInt32(t)).ToList();
                    //var category = _ICategoryRepository.GetAll().Where(t => ids.Contains(t.CategoryId));

                    SqlParameter[] param = {
                        new SqlParameter("@CategoryId", Id),
                        new SqlParameter("@UserId", CurrentContext.UserDetail.UserId)
                    };
                    var isSuccess = _ICategoryRepository.DeleteRecordSproc("DeleteCategory", param, ConfigurationSettings.DBConnection);

                    return Json(new { success = "true", ReturnMsg = "Category deleted successfully.", PartialviewContent = "" });
                }
                else
                {
                    return Json(new { success = "false", ReturnMsg = "Category does not exist.", PartialviewContent = "" });
                }
            }
            catch (Exception ex)
            {
                ex.SetLog("Master/DeleteMultipleCategory");
                return Json(new { success = "false", ReturnMsg = "Error", PartialviewContent = "" });
            }
        }
        #endregion

        #region :: SUB CATEGORY ::
        public IActionResult SubCategory()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ManageSubCategory(int id = 0)
        {
            var subCategory = new SubCategoryModel();
            try
            {
                if (id != 0)
                {
                    subCategory = _ISubCategoryRepository.GetById(id).ToModel();

                }
                return PartialView(subCategory);
            }
            catch (Exception ex)
            {
                ex.SetLog("Logbook/ManageSubCategory");
                return PartialView(subCategory);
            }
        }

        [HttpPost]
        public IActionResult ManageSubCategory(SubCategoryModel subCategory)
        {
            try
            {
                var ObjSubCategory = subCategory.SubCategoryId != 0 ? _ISubCategoryRepository.GetByIdWithNoTracking(subCategory.SubCategoryId) : null;
                if (ObjSubCategory == null || !string.Equals(ObjSubCategory.Name.Trim().ToLower(), subCategory.Name.Trim().ToLower(), StringComparison.OrdinalIgnoreCase))
                {
                    var subCategoryDb = _ISubCategoryRepository.GetAll(x => x.CategoryId == subCategory.CategoryId && string.Equals(x.Name.Trim().ToLower(), subCategory.Name.Trim().ToLower()) && !x.IsDelete).FirstOrDefault();
                    if (subCategoryDb != null)
                        return Json(new { success = "false", ReturnMsg = "SubCategory already exists.", PartialviewContent = this.RenderPartialViewToString("ManageSubCategory", subCategory, _serviceProvider) });
                }
                if (ModelState.IsValid)
                {
                    if (subCategory.SubCategoryId == 0)
                    {
                        SubCategory SubCategoryObj = _ISubCategoryRepository.InsertAndGetObj(subCategory.ToEntity(), CurrentContext.UserDetail.UserId);
                        return Json(new { success = "true", ReturnMsg = "SubCategory saved.", PartialviewContent = "" });
                    }
                    else
                    {
                        _ISubCategoryRepository.Update(subCategory.ToEntity(), CurrentContext.UserDetail.UserId);
                        return Json(new { success = "true", ReturnMsg = "SubCategory updated.", PartialviewContent = "" });
                    }
                }
                else
                {
                    string _message = string.Join(Environment.NewLine, ModelState.Values
                                               .SelectMany(x => x.Errors)
                                               .Select(x => x.ErrorMessage));
                    return Json(new { success = "false", ReturnMsg = _message, PartialviewContent = this.RenderPartialViewToString("ManageSubCategory", subCategory, _serviceProvider) });
                }
            }
            catch (Exception ex)
            {
                ex.SetLog("Logbook/ManageSubCategory");

hospins/Views/Logbook/Category.cshtml
@{
    ViewData["Title"] = "Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
   <ol class="breadcrumb">
      <li><a href="#"><i class="pe-7s-home"></i> Dashboard</a></li>
      <li><a href="#">Logbook</a></li>
      <li class="active"><span>Category</span> List</li>
   </ol>

   <!-- load messages -->
   <div class="se-pre-con" style="display: none;"></div>

   <!-- load custom page -->
   <div class="row">
      <div class="col-sm-12">
         <div class="panel panel-bd lobidrag">
            <div class="panel-heading">
               <div class="panel-title">
                  <h4>Category List </h4>
               </div>
            </div>
            <div class="panel-body">
               <div id="paid_CustomerList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                  <div class="row">
                     <div class="col-sm-12">
                        @Html.AntiForgeryToken()
						<table id="tblCategory" class="table table-bordered common-data-table" style="width:100%"></table>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<div class="modal fade" tabindex="-1" id="modalCategory" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg">
		<div class="modal-content" id="contentCategory"></div>
	</div>
</div> 

@section scripts{
	<script src="~/js/pages/Category.js" asp-append-version="true"></script>
    <script type="text/javascript">
		var addCategoryURL = '@Url.Action("ManageCategory", "Logbook", new { area = "" })';
		var statusCategoryURL = '@Url.Action("StatusCategory", "Logbook", new { area = "" })';
		var deleteCategoryURL = '@Url.Action("DeleteMultipleCategory", "Logbook", new { area = "" })';
	</script>
}

hospins/Views/Logbook/ManageCategory.cshtml
@using hospins.Repository.Infrastructure;
@model hospins.Models.CategoryModel
@{
    ViewData["Title"] = "Manage Category";
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h5 class="modal-title" id="exampleModalLongTitle">Manage Category</h5>
</div>
<form asp-area = "" asp-controller="Logbook" asp-action="ManageCategory" method="post" id="frmCategory" role="form">
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <input type="hidden" asp-for="CategoryId" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label>Category&nbsp;<span class="text-danger">*</span>:</label>
            <input type="text" class="form-control" asp-for="Name" autocomplete="off" maxlength="250" autofocus />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="form-group">
                    <label>Is Active&nbsp;:</label>
                    <div class="col-md-12 padd-left-right-0">
                        <label class="switch small-switch switch-danger">
                            <input type="checkbox" asp-for="IsActive"/>
                            <span class="switch-slider"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-sm-12">
                <div class="form-group">
                    <label>Sort Order&nbsp;:</label>
                    <input type="text" class="numberwithfloat form-control" asp-for="SortOrder" autocomplete="off"/>
                    <span class="text-danger" asp-validation-for="SortOrder"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
</form>
<script src="~/js/jquery.validate.min.js"></script>
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>

hospins/Views/Logbook/ManageLogbook.cshtml
@using hospins.Infrastructure;
@using hospins.Repository.Infrastructure;
@model hospins.Models.LogbookModel
@{
    ViewData["Title"] = "Manage Logbook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
    <ol class="breadcrumb">
        <li><a href="#">Logbook</a></li>
        <li class="active">Add/Edit Logbook</li>
    </ol>
    <!-- load messages -->
    <div class="se-pre-con"></div>
    <!-- load custom page -->
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-bd lobidrag">
                <div class="panel-heading">
                    <div class="panel-title">
                        <h4>Add Logbook</h4>
                    </div>
                </div>
                <div class="panel-body">
                    <form asp-controller="Logbook" asp-action="ManageLogbook" method="post" id="frmLogbook" role="form">
                        @Html.AntiForgeryToken()
                        <input type="hidden" asp-for="LogbookId" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="col-md-12 form-group">
                            <label class="col-sm-2 col-form-div">Log Book Id</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" asp-for="SequnceId" disabled/>
                            </div>
                        </div>
                        <div class="col-md-12 form-group">
                            <label class="col-sm-2 col-form-div">Log Book <i class="text-danger">*</i></label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" asp-for="Name" autocomplete="off" maxlength="100" autofocus placeholder="Log Book"/>
                                <span class="text-danger" asp-validation-for="Name"></span>
                            </div>
                        </div>
                        
                        <div class="col-md-12 form-group">
                            <label for="last_name" class="col-sm-2 col-form-div">Date<i class="text-danger">*</i></label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control custdatepicker" placeholder="Date" asp-for="Date" asp-format="{0:MMM dd, yyyy}" autocomplete="off"/>
                                <span class="text-danger" asp-validation-for="Date"></span>
                            </div>
                        </div>
                        <div class="col-md-12 form-group">
                            <label class="col-sm-2 col-form-div">Category</label>
                            <div class="col-sm-4">
                                <drop-down-list class="select2-selection" asp-for="CategoryId" asp-mode="Category" asp-default="Select Category"></drop-down-list>
                            </div>
                        </div>
                        <div class="col-md-12 form-group">
                            <label class="col-sm-2 col-form-div">SubCategory</label>
                            <div class="col-sm-4">
                                <select class="select2-selection w-100" title="Select SubCategory" asp-for="SubCategoryId"></select>
                            </div>
                        </div>
                        <div class="col-md-12 form-group">
                            <label class="col-sm-2 col-form-div">Description</label>
                            <div class="col-sm-4">
                                <textarea cols="10" rows="3" class="form-control" asp-for="Description"></textarea>
                            </div>
                        </div>
                        <div class="col-md-12 form-group">
                            <label class="col-sm-2 col-form-div">Assisgn to</label>
                            <div class="col-sm-4">
                                <drop-down-list class="select2-selection" asp-for="AssisgnTo" asp-mode="User" asp-default="Select AssisgnTo"></drop-down-list>
                            </div>
                        </div>
                        <div class="col-md-12 form-group">
                            <label class="col-sm-2 col-form-div">Priority</label>
                            <div class="col-sm-4">
                                <drop-down-list class="select2-selection" asp-for="PriorityId" asp-mode="Priority" asp-default="Select Priority"></drop-down-list>
                            </div>
                        </div>

                        <div class="form-group text-right">
                            <a asp-area = "" asp-controller="Logbook" asp-action="Index" class="btn btn-default">Back</a>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script> 
    <script>
        if ('@ViewBag.success' == "true" && '@ViewBag.message' != "") {
            Popuphtml('@ViewBag.message', 'success');
        }
        else if ('@ViewBag.success' == "false" && '@ViewBag.message' != "") {
            Popuphtml('@ViewBag.message', 'error');
        }
        var bindSubCategoryURL = '@Url.Action("BindSubCategory", "Logbook")';

        $(document).ready(function(){
            $("#SubCategoryId").select2({allowClear: true,placeholder: "Select option"});
            $('.custdatepicker').datetimepicker({
                "allowInputToggle": true,
                "showClose": true,
                "showClear": true,
                "showTodayButton": true,
                "format": "MMM, DD YYYY",
                "useCurrent": false
            });

            $("#CategoryId").on("change",function(){
                bindSubCategory($(this).val());
            });

            if(~~'@Model.CategoryId' > 0)
            {
                $("#CategoryId").trigger("change");
            }
        });

        function bindSubCategory(selectedValue) {
            AjaxCall(bindSubCategoryURL+"?id="+selectedValue, "GET", null, function(res) {
                if (res.success == 'true') {
                    $("#SubCategoryId").html('');
                    var optionHtml = "<option>Select SubCategory</option>";
                    $.each(res.returnMsg, function(j, o) {
                        optionHtml +='<option value="'+ o["subCategoryId"] +'">'+ o["name"] +'</option>';        
                    });
                    $("#SubCategoryId").html(optionHtml);
                    $("#SubCategoryId").val(@Model.SubCategoryId);
                }
                else {
                    $("#SubCategoryId").html('');
                    $("#SubCategoryId").val(null);
                }
                $("#SubCategoryId").select2({
                    placeholder: "Select option",
                    allowClear: true
                });
            });
        }
    </script>
}

hospins/Views/Logbook/ManagePriority.cshtml
@using hospins.Repository.Infrastructure;
@model hospins.Models.PriorityModel
@{
    ViewData["Title"] = "Manage Priority";
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h5 class="modal-title" id="exampleModalLongTitle">Manage Priority</h5>
</div>
<form asp-area = "" asp-controller="Logbook" asp-action="ManagePriority" method="post" id="frmPriority" role="form">
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <input type="hidden" asp-for="PriorityId" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label>Priority&nbsp;<span class="text-danger">*</span>:</label>
            <input type="text" class="form-control" asp-for="Name" autocomplete="off" maxlength="250" autofocus />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="form-group">
                    <label>Is Active&nbsp;:</label>
                    <div class="col-md-12 padd-left-right-0">
                        <label class="switch small-switch switch-danger">
                            <input type="checkbox" asp-for="IsActive"/>
                            <span class="switch-slider"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-sm-12">
                <div class="form-group">
                    <label>Sort Order&nbsp;:</label>
                    <input type="text" class="numberwithfloat form-control" asp-for="SortOrder" autocomplete="off"/>
                    <span class="text-danger" asp-validation-for="SortOrder"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
</form>
<script src="~/js/jquery.validate.min.js"></script>
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>

hospins/Views/Logbook/ManageSubCategory.cshtml
@using hospins.Repository.Infrastructure;
@model hospins.Models.SubCategoryModel
@{
    ViewData["Title"] = "Manage SubCategory";
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h5 class="modal-title" id="exampleModalLongTitle">Manage SubCategory</h5>
</div>
<form asp-area = "" asp-controller="Logbook" asp-action="ManageSubCategory" method="post" id="frmSubCategory" role="form">
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <input type="hidden" asp-for="SubCategoryId" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label>SubCategory&nbsp;<span class="text-danger">*</span>:</label>
            <input type="text" class="form-control" asp-for="Name" autocomplete="off" maxlength="250" autofocus />
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <label>Category&nbsp;<span class="text-danger">*</span>:</label>
            <drop-down-list asp-for="CategoryId" asp-mode="Category" asp-default="Select Category"></drop-down-list>
            <span class="text-danger" asp-validation-for="CategoryId"></span>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="form-group">
                    <label>Is Active&nbsp;:</label>
                    <div class="col-md-12 padd-left-right-0">
                        <label class="switch small-switch switch-danger">
                            <input type="checkbox" asp-for="IsActive"/>
                            <span class="switch-slider"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-sm-12">
                <div class="form-group">
                    <label>Sort Order&nbsp;:</label>
                    <input type="text" class="numberwithfloat form-control" asp-for="SortOrder" autocomplete="off"/>
                    <span class="text-danger" asp-validation-for="SortOrder"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
</form>
<script src="~/js/jquery.validate.min.js"></script>
<script src="~/js/jquery.validate.unobtrusive.min.js"></script>
<script>
    $("#CategoryId").select2({
        placeholder: "Select option",
        allowClear: true
    });
</script>

hospins/Views/Logbook/Priority.cshtml
@{
    ViewData["Title"] = "Priority";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
   <ol class="breadcrumb">
      <li><a href="#"><i class="pe-7s-home"></i> Dashboard</a></li>
      <li><a href="#">Logbook</a></li>
      <li class="active"><span>Priority</span> List</li>
   </ol>

   <!-- load messages -->
   <div class="se-pre-con" style="display: none;"></div>

   <!-- load custom page -->
   <div class="row">
      <div class="col-sm-12">
         <div class="panel panel-bd lobidrag">
            <div class="panel-heading">
               <div class="panel-title">
                  <h4>Priority List </h4>
               </div>
            </div>
            <div class="panel-body">
               <div id="paid_CustomerList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                  <div class="row">
                     <div class="col-sm-12">
                        @Html.AntiForgeryToken()
						<table id="tblPriority" class="table table-bordered common-data-table" style="width:100%"></table>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<div class="modal fade" tabindex="-1" id="modalPriority" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg">
		<div class="modal-content" id="contentPriority"></div>
	</div>
</div> 

@section scripts{
	<script src="~/js/pages/Priority.js" asp-append-version="true"></script>
    <script type="text/javascript">
		var addPriorityURL = '@Url.Action("ManagePriority", "Logbook", new { area = "" })';
		var statusPriorityURL = '@Url.Action("StatusPriority", "Logbook", new { area = "" })';
		var deletePriorityURL = '@Url.Action("DeleteMultiplePriority", "Logbook", new { area = "" })';
	</script>
}

hospins/Views/Logbook/SubCategory.cshtml
@{
    ViewData["Title"] = "SubCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
   <ol class="breadcrumb">
      <li><a href="#"><i class="pe-7s-home"></i> Dashboard</a></li>
      <li><a href="#">Logbook</a></li>
      <li class="active"><span>SubCategory</span> List</li>
   </ol>

   <!-- load messages -->
   <div class="se-pre-con" style="display: none;"></div>

   <!-- load custom page -->
   <div class="row">
      <div class="col-sm-12">
         <div class="panel panel-bd lobidrag">
            <div class="panel-heading">
               <div class="panel-title">
                  <h4>SubCategory List </h4>
               </div>
            </div>
            <div class="panel-body">
               <div id="paid_CustomerList_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                  <div class="row">
                     <div class="col-sm-12">
                        @Html.AntiForgeryToken()
						<table id="tblSubCategory" class="table table-bordered common-data-table" style="width:100%"></table>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<div class="modal fade" tabindex="-1" id="modalSubCategory" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg">
		<div class="modal-content" id="contentSubCategory"></div>
	</div>
</div> 

@section scripts{
	<script src="~/js/pages/SubCategory.js" asp-append-version="true"></script>
    <script type="text/javascript">
		var addSubCategoryURL = '@Url.Action("ManageSubCategory", "Logbook", new { area = "" })';
		var statusSubCategoryURL = '@Url.Action("StatusSubCategory", "Logbook", new { area = "" })';
		var deleteSubCategoryURL = '@Url.Action("DeleteMultipleSubCategory", "Logbook", new { area = "" })';
	</script>
}